src/AppBundle/Entity/Match.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\TournamentFinalRound;
use AppBundle\Entity\Team;
use AppBundle\Entity\Match;
use AppBundle\Entity\TournamentGroup;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Match
 *
 * @ORM\Table(name="match_game")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MatchRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Match extends LbmExtensionEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
    * @ORM\ManyToOne(targetEntity="Team")
    * @ORM\JoinColumn(name="team_A_id", referencedColumnName="id")
    */
    private $teamA;

    /**
    * @ORM\ManyToOne(targetEntity="Team")
    * @ORM\JoinColumn(name="team_B_id", referencedColumnName="id")
    */
    private $teamB;

    /**
    * @ORM\ManyToOne(targetEntity="TournamentFinalRound", inversedBy="matchs")
    * @ORM\JoinColumn(name="final_round_id", referencedColumnName="id")
    */
    private $finalRound;

    /**
    * @ORM\ManyToOne(targetEntity="TournamentGroup", inversedBy="matchs")
    * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
    */
    private $group;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=50, nullable=true)
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="time_start", type="time",nullable=true)
     */
    private $timeStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="time_end", type="time",nullable=true)
     */
    private $timeEnd;

    /**
     * @var int
     *
     * @ORM\Column(name="position", type="integer", nullable=true)
     */
    private $position;

    /**
     * @var int
     *
     * @ORM\Column(name="pointA", type="integer", nullable=true)
     */
    private $pointA;

    /**
     * @var int
     *
     * @ORM\Column(name="pointB", type="integer", nullable=true)
     */
    private $pointB;

    /**
     * @var string
     *
     * @ORM\Column(name="winner", type="string", length=20, nullable=true)
     */
    public $winner;

    /**
     * @var string
     *
     * @ORM\Column(name="type_match", type="string", length=20, nullable=true)
     */
    public $typeMatch;

    /**
     *
     * @ORM\ManyToMany(targetEntity="User", inversedBy="matchs")
     * @ORM\JoinTable(name="matchs_users")
     */
    private $users;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function resetValues()
    {
        $this->setStatus('EMPTY');
        $this->setPointA(null);
        $this->setPointB(null);
        $this->setWinner(null);
        $this->setTimeStart(null);
        $this->setTimeEnd(null);

    }

    public function setTeamA(Team $team)
    {
        $this->teamA = $team;
        return $this;
    }

    public function getTeamA()
    {
        return $this->teamA;
    }

    public function setTeamB(Team $team)
    {
        $this->teamB = $team;
        return $this;
    }

    public function getTeamB()
    {
        return $this->teamB;
    }

    public function getTeamNameA()
    {
        return $this->getTeamName('teamA');
    }

    public function getTeamNameB()
    {
        return $this->getTeamName('teamB');
    }

    public function getTeamName($team)
    {
        $name = null;
        if($team == 'teamA' && $this->getTeamA()) $name = $this->getTeamA()->getName();
        if($team == 'teamB' && $this->getTeamB()) $name = $this->getTeamB()->getName();
        if($team == $this->getWinner()) {
          $name = "<span class='winner'>".$name.'</span>';
        }
        return $name;
    }

    public function setFinalRound(TournamentFinalRound $finalRound)
    {
        $this->finalRound = $finalRound;
        return $this;
    }

    public function getFinalRound()
    {
        return $this->finalRound;
    }

    public function setGroup(TournamentGroup $group)
    {
        $this->group = $group;
        return $this;
    }

    public function getGroup()
    {
        return $this->group;
    }

    public function getTournament()
    {
        if( $this->getGroup() ) return $this->getGroup()->getTournament();
        if( $this->getFinalRound() ) return $this->getFinalRound()->getTournament();
        return null;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return Match
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set timeStart
     *
     * @param \DateTime $time
     *
     * @return Match
     */
    public function setTimeStart($time)
    {
        $this->timeStart = $time;

        return $this;
    }

    /**
     * Get timeStart
     *
     * @return \DateTime
     */
    public function getTimeStart()
    {
        return $this->timeStart;
    }


    /**
     * Set timeEnd
     *
     * @param \DateTime $time
     *
     * @return Match
     */
    public function setTimeEnd($time)
    {
        $this->timeEnd = $time;

        return $this;
    }

    public function setTypeMatch($typeMatch)
    {
        $this->typeMatch = $typeMatch;
        return $this;
    }

    public function getTypeMatch()
    {
        return $this->typeMatch;
    }

    public function getTypeMatchString()
    {
      if($this->getTypeMatch() == "A") return "aller";
      if($this->getTypeMatch() == "R") return "retour";
      return null;

    }

    public function addUser($user)
    {
        $this->users[] = $user;
        $user->addMatch($this);
        return $this;
    }

    public function removeUser($user)
    {
        $this->users->removeElement($user);
        return $this;
    }

    public function getUsers($role = null)
    {
        if($role) {
          $result = new ArrayCollection;
            foreach($this->users as $user) {
                if($user->getRoleString() == $role) $result[] = $user;
            }
            return $result;
        }
        return $this->users;
    }

    public function getReferees()
    {
        return $this->getUsers('REFEREE');
    }

    public function getRefereeIdList()
    {
      if(!$referees = $this->getReferees()) return null;
      $arr = [];
      foreach($referees as $ref)
      {
        $arr[$ref->getId()] = $ref->getId();
      }
      return $arr;
    }

    /**
     * Get timeEnd
     *
     * @return \DateTime
     */
    public function getTimeEnd()
    {
        return $this->timeEnd;
    }

    /**
     * Set position
     *
     * @param integer $position
     *
     * @return Match
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set pointA
     *
     * @param integer $pointA
     *
     * @return Match
     */
    public function setPointA($pointA)
    {
        $this->pointA = $pointA;

        return $this;
    }

    /**
     * Get pointA
     *
     * @return int
     */
    public function getPointA()
    {
        return $this->pointA;
    }

    /**
     * Set pointB
     *
     * @param integer $pointB
     *
     * @return Match
     */
    public function setPointB($pointB)
    {
        $this->pointB = $pointB;

        return $this;
    }

    public function getScore($separator = ' - ')
    {
        return $this->getPointA().$separator.$this->getPointB();
    }

    /**
     * Get pointB
     *
     * @return int
     */
    public function getPointB()
    {
        return $this->pointB;
    }

    /**
     * Set winner
     *
     * @param string $winner
     *
     * @return Match
     */
    public function setWinner($winner)
    {
        $this->winner = $winner;

        return $this;
    }

    public function getWinner()
    {
        return $this->winner;
    }



    /**
     * Get winner
     *
     * @return Team|null
     */
    public function getWinnerTeam()
    {
        if($this->winner == 'none') return 'none';
        if($this->winner == 'teamA') return $this->getTeamA();
        if($this->winner == 'teamB') return $this->getTeamB();
        return null;
    }

}

src/AppBundle/Controller/GameController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\Tournament;
use AppBundle\Entity\GameOptions;

use AppBundle\Service\GameManager;

class GameController extends Controller
{

    private $gameManager;

    public function __construct(GameManager $gameManager)
    {
            $this->gameManager = $gameManager;
    }

    /**
     * @Route("/creation-du-tournoi/{tournamentId}", name="createGame")
     */
    public function indexAction(Request $request, $tournamentId = null)
    {
        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);

        // block acces to init
        if($tournament->getIsInit() == 1) {
          return $this->redirectToRoute('showMatchGroup', ['tournamentId' => $tournamentId]);
        }

        $val = 2;
        while($val <= $tournament->countNbTeams() ) {
          $maxTeamFinalRoundOption[] = $val;
          $val = $val*2;
        }

        $maxGroup = floor($tournament->countNbTeams()/3);

        return $this->render('AppBundle:game:create.html.twig', ['tournament' => $tournament, 'maxGroup' => $maxGroup, 'maxTeamFinalRoundOption' => $maxTeamFinalRoundOption]);
    }

    /**
     * @Route("/initialisation-partie", name="initGame")
     */
    public function initGameAction(Request $request, GameManager $gameManager)
    {
        $tournamentId = $request->get('tournamentId');
        $gameOptionsArray = $request->get('data');

        $em = $this->getDoctrine()->getManager();
        $tournament = $em->getRepository(Tournament::class)->find($tournamentId);

        ($request->get('resetForce')) ? $resetForce = true : $resetForce = false;

        if(!$tournamentInit = $gameManager->initTournament($tournament, $gameOptionsArray, $resetForce)) {
            $this->addFlash('warning',
                            'Impossible d\'initier le tournoi, les groupes sont déjà créés.<br/>Vous pouvez essayer en forçant la création.'
                          );
            return $this->redirectToRoute('createGame', ['tournamentId' => $tournament->getId()]);
        }

        $gameManager->setTournament($tournament);
        $gameManager->autoBindGroups();
        $gameManager->validGroups();

        return $this->redirectToRoute('showMatchGroup', ['tournamentId' => $tournamentId]);
    }


    /**
     * @Route("/remettre-zero-tournoi/{tournamentId}", name="resetGame")
     */
    public function resetGame(Request $request, $tournamentId)
    {

        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);
        $this->gameManager->setTournament($tournament)->resetTournament('groups')->resetTournament('matchs');
        return $this->redirectToRoute('showTournament', ['id' => $tournamentId]);
    }

    /**
     * @Route("/simuler-le-tournoi/{tournamentId}", name="simulateTournament")
     */
    public function simulateTournament(Request $request, $tournamentId, GameManager $gameManager)
    {

        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);
        $gameManager->setTournament($tournament)->simulateTournament();
        return $this->redirectToRoute('showMatchGroup', ['tournamentId' => $tournamentId]);
    }


    /**
     * @Route("/voir-les-matchs/{tournamentId}", name="showMatchGroup")
     */
    public function showMatchGroup(Request $request, GameManager $gameManager, $tournamentId)
    {
        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);
        $gameManager->setTournament($tournament);
        return $this->render('AppBundle:game:matchGroup.html.twig', ['tournament' => $tournament,'gameManager' => $gameManager]);
    }

    /**
     * @Route("/passer-en-phase-finale/{tournamentId}", name="finalRoundPrepar")
     */
    public function finalRoundPrepar(Request $request, GameManager $gameManager, $tournamentId)
    {

        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);
        $val = 2;
        while($val <= $tournament->countNbTeams() ) {
          $maxTeamFinalRoundOption[] = $val;
          $val = $val*2;
        }
        return $this->render('AppBundle:game:editFinalRound.html.twig', ['tournament' => $tournament,'gameManager' => $gameManager, 'maxTeamFinalRoundOption' => $maxTeamFinalRoundOption]);
    }

    /**
     * @Route("/initier-phase-finale", name="initFinalRound")
     */
    public function initFinalRound(Request $request, GameManager $gameManager)
    {
        $tournamentId = $request->get('tournamentId');
        $totalTeams = $request->get('totalTeams');

        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);

        if($tournament->getCompetitionType() != "FINAL-ROUND") {
          $gameManager->setTournament($tournament)->initFinalRound($totalTeams);
        }

        return $this->redirectToRoute('showMatchFinalRound', ['tournamentId' => $tournamentId]);

    }

    /**
     * @Route("/voir-les-matchs-phase-finale/{tournamentId}", name="showMatchFinalRound")
     */
    public function showMatchFinalRound(Request $request, GameManager $gameManager, $tournamentId)
    {
        $tournament = $this->getDoctrine()->getManager()->getRepository(Tournament::class)->find($tournamentId);
        $gameManager->setTournament($tournament);
        return $this->render('AppBundle:game:finalRound.html.twig', ['tournament' => $tournament,'gameManager' => $gameManager]);
    }




}

src/AppBundle/Resources/views/game/classement.html.twig
<table id="ranking" class="table table--zebra">
  <thead>
      <tr>
        <th>Club</td>
        <th class="rankingValue">MJ</th>
        <th class="rankingValue">V</th>
        <th class="rankingValue">N</th>
        <th class="rankingValue">D</th>
        <th class="rankingValue">BP</th>
        <th class="rankingValue">BC</th>
        <th class="rankingValue">DB</th>
        <th class="rankingValue">PT</th>
      </tr>
  </thead>
  <tbody>
    {% set i = 0 %}
    {% for ranking in tournament.rankings %}
          {% set i = i + 1 %}
          <tr>
              <td style="color: #0275D8; font-weight: 800">{{ i }} - {{ ranking.team.name }}</td>
              <td>{{ ranking.MJ}}</td>
              <td>{{ ranking.V}}</td>
              <td>{{ ranking.N}}</td>
              <td>{{ ranking.D}}</td>
              <td>{{ ranking.BP}}</td>
              <td>{{ ranking.BC}}</td>
              <td>{{ ranking.DB}}</td>
              <td style="color: #0275D8">{{ ranking.PTS}}</td>
          </tr>
    {% endfor %}
  </tbody>
</table>

<section class="grid-6-small-2">
    {% for group in tournament.groups %}
        <div>
            <h3>{{ group.name}}</h3>
            <ol>
              {% for ranking in group.rankings %}
                  <li>
                      {{ ranking.team.name }}
                      <div style="float: right; width: 30px">
                        {{ ranking.PTS}}
                      </div>
                  </li>
              {% endfor %}
            </ol>
        <div>
    {% endfor %}
</section>

src/AppBundle/Resources/views/game/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <p style="font-size: 1.2em">
    Welcome !
    <br/>
    Vous avez {{ tournament.countNbTeams }} équipes participantes.<br/>
    <br/>
    Vous pouvez maintenant créer votre tournoi.<br/>
    <br/>
  </p>
  <br/>
  <form  action="{{ path('initGame')}}" method="post" >

      <input type="hidden" value="{{tournament.id}}" name="tournamentId"/>

      <h2 style="text-align: center">Type de tournoi</h2>
      <select name = "data[type]" class="fullWidth typeSelect" style="height: 40px" required>
        <option selected/>
        <option value="group">Phase de groupes</option>
        <option value="finalRound">Phase finale</option>
      </select>

      <br/><br/>

      <p id="groupOptions"  class="typeSelectOptions" style="font-size: 1.2em; display: none">
        Nombre de groupes&nbsp;&nbsp;&nbsp;
        <select name="data[nbGroups]">
          {% for i in 1 .. maxGroup %}
            <option value="{{i}}" selected>
              {{ i }}
            </option>
          {% endfor %}
        </select>

        <br/>
        Rencontre

        <select name="data[hasReturnMatch]">
            <option value="0" selected>Simple
            </option>
            <option value="1">Aller/Retour
            </option>
        </select>
      </p>

      <p id="finalRoundOptions" class="typeSelectOptions" style="font-size: 1.2em; display: none">
        Nombre d'équipe qualifiées&nbsp;&nbsp;&nbsp;
        <select name="data[nbFinalRound]">
          {% for val in maxTeamFinalRoundOption %}
            <option value="{{val}}" >
              {{ val }}
            </option>
          {% endfor %}
        </select>
      </p>
      <br/><br/>

      {% if tournament.isInit == 1 %}
        <input type='hidden' name="resetForce" value="0"/>

        <p class="alert--danger" style="text-align: justify;">
        Les options du tournoi, ainsi que la répartition des équipes ont déjà été faites pour ce tournoi.<br/>
        Pour le refaire, vous devez forcer en cochant la case suivante : <input type="checkbox" name="resetForce"/>
        </p>
        <br/>
      {% endif %}


      <br/>
      <input style="height: 80px; font-size: 2em" type="submit" class="btn--primary fullWidth" value="Valider"/>

  </form>
<br/><br/>

  <p class="alert--danger" style="font-size: 2em; text-align: center">
  ATTENTION
  </p>
  <br/>
  <p class="alert">
  En cliquant sur valider, les équipes vont être aléatoirement réparties dans le tournoi.<br/>
  </p>
  <br/>

  <p class="alert">
    Une fois la validation effectuée, vous ne pourrez plus ajouter d'équipes.
  </p>
  <br/>
  <p class="alert">
    Si vous optez pour un tournoi avec des phases de groupes, vous pourrez passer en phase finale, une fois tous les matchs joués.
  </p>
  <br/>

  <script>
    $('.typeSelect').change(function() {
      $('.typeSelectOptions').hide();
      let target = $(this).val();
      $('#'+target+'Options').show();
    });
  </script>


{% endblock %}

src/AppBundle/Resources/views/game/editFinalRound.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<p style="font-size: 1.2em">
  Welcome !
  <br/>
  Vous avez {{ tournament.countNbTeams }} équipes participantes.<br/>
  <br/>
  Vous pouvez créer la phase finale de votre tournoi<br/>
  <br/>
</p>
<br/>
<form  action="{{ path('initFinalRound')}}" method="post" >

    <input type="hidden" value="{{tournament.id}}" name="tournamentId"/>

    <p id="finalRoundOptions" class="typeSelectOptions" style="font-size: 1.2em;">
      Nombre d'équipe qualifiées&nbsp;&nbsp;&nbsp;
      <select name="totalTeams">
        {% for val in maxTeamFinalRoundOption %}
          <option value="{{val}}" >
            {{ val }}
          </option>
        {% endfor %}
      </select>
    </p>
    <br/><br/>


    <br/>
    <input style="height: 80px; font-size: 2em" type="submit" class="btn--primary fullWidth" value="Valider"/>

</form>
<br/><br/>

<br/>
<p class="alert">
La répartition se fera de manière alétoire avec un système de tête de série.
</p>
<br/>
<p class="alert">
Le même nombre d'équipe par groupe est sélectionné. Dans la mesure du possible.
</p>
<br/>


{% endblock %}

src/AppBundle/Resources/views/game/finalRound.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>
  {% if tournament.hasGroupRound == 1 %}
    <a href="{{ path('showMatchGroup', {'tournamentId' : tournament.id})}}" style="float: left" title="voir phase finale">
      <i class="fas fa-exchange-alt"></i>
    </a>
  {% endif %}
  {% if tournament.isOpen == 1%}
      <i class="fas fa-running"></i>
  {% endif %}
  {{ tournament.name }}<br/>
  <span style="font-weight: normal; font-size: 0.7em; font-style: italic">Tableau final</span>
</h1>


<div id="finalRound">

  {% for round in tournament.finalRounds %}

      <div id="round-{{round.step}}" class="stepContent">
        <br/>
        <h2 style="font-size: 1.3em">{{ round.name|capitalize}}</h2>

        {% if round.step == 0 and (round.tournament.winner is not null) %}
            <div class="matchFinalRound">
              <h1>{{ round.tournament.winner.name}}</h1>
            </div>

        {% else %}


              {% for match in round.matchs %}

                  <div class="matchFinalRound">

                    <ul>
                      <a href="{{ path('showMatch', {id: match.id})}}">
                        <i class="far fa-eye"></i>
                      </a>
                      <li>
                        {{ match.teamNameA|raw }}
                        <div class="point">
                          {{ match.pointA }}
                        </div>
                      </li>
                      <li>
                        {{ match.teamNameB|raw }}
                        <div class="point">
                          {{ match.pointB }}
                        </div>
                      </li>

                    </ul>

                  </div>

              {% endfor %}
          {% endif %}

      </div>

  {% endfor %}





</div>

{% endblock %}

src/AppBundle/Resources/views/game/matchGroup.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% set currentTypeMatch = "" %}

<h1>
  {% if tournament.competitionType == 'FINAL-ROUND' %}
    <a href="{{ path('showMatchFinalRound', {'tournamentId' : tournament.id})}}" style="float: left" title="voir phase finale">
    <i class="fas fa-exchange-alt"></i>
    </a>
  {% endif %}
  {% if tournament.isOpen == 1%}
      <i class="fas fa-running"></i>
  {% endif %}
  {{ tournament.name }}
</h1>

<div class="tabs js-tabs">
  <nav class="tabs-menu">
    {% if tournament.competitionType == 'FINAL-ROUND' %}
      <a href="#tab4" class="tabs-menu-link blockTab is-active">Equipes Qualifées</a>
      {% set is_active = "" %}
      {% set display = "display: none" %}

    {% else %}
      {% set is_active = "is-active" %}
      {% set display = "" %}
    {% endif %}
    <a href="#tab1" class="tabs-menu-link blockTab {{ is_active }}">Voir les Matchs</a>
    <a href="#tab2" class="tabs-menu-link blockTab">Voir le Classement</a>
    <a href="#tab3" class="tabs-menu-link blockTab">Voir les Groupes</a>

  </nav>

  {% if tournament.isOpen != 1 %}
    <a href="{{ path('openTournament', {'tournamentId' : tournament.id})}}">
      <div class="alert--warning" style="text-align: center">
        Le tournoi n'est pas "ouvert",<br/>
        pour démarrer la compétition cliquez ici.
      </div>
    </a>
  {% endif %}

  <div id="tab1" class="tabs-content-item groupList" style="{{ display}}">

      {% for group in tournament.groups %}
          <div class="groupName">
              <h3>{{ group.name}}</h3>
          </div>
          <div class="teamsGroup">
              <ul>
                {% for match in group.matchs %}
                  {% if tournament.gameOptions.hasReturnMatch == 1 %}
                        {% if match.typeMatch != currentTypeMatch %}
                          <h4 style="color: white; font-size: 1em">{{ match.typeMatchString|capitalize }}</h4>
                          {% set currentTypeMatch = match.typeMatch %}
                        {% endif %}
                  {% endif %}
                  <li>
                    {{match.teamName('teamA')|raw}} -  {{match.teamName('teamB')|raw}}

                    {% if tournament.isOpen == 1 and tournament.nbMatchLeft != 0 and is_granted(['ROLE_MANAGER', 'ROLE_ADMIN']) %}
                      <span style="float: right; margin-left: 50px;">
                          <a href="{{ path('showMatch', {id: match.id})}}">
                              <i class="far fa-eye"></i>
                          </a>
                      </span>
                    {% endif %}
                    <span style="float: right">
                        {{ match.score }}
                    </span>


                  </li>
                {% endfor %}
              </ul>
          </div>

      {% endfor %}
  </div>
  <div id="tab2" class="tabs-content-item" style="display: none">
      {{ include('AppBundle:game:classement.html.twig', { "tournament" : tournament} ) }}
  </div>

  <div id="tab3" class="tabs-content-item" style="display: none">
      {% for group in tournament.groups %}
          <div class="groupName">
              <h3>{{ group.name}}</h3>
          </div>
          <div class="teamsGroup">
              <ul>
                {% for team in group.teams %}
                  <li>
                    {{team.name}}
                  </li>
                {% endfor %}
              </ul>
          </div>

      {% endfor %}
  </div>

  {% if tournament.nbMatchLeft == 0 %}
    <div id="tab4" class="tabs-content-item groupList">
      Liste
      <div class="teamsGroup">
        <ul>
          {% for teamSelected in tournament.teamsSelecteds %}
            <li>
              {{teamSelected.name}}
            </li>
          {% endfor %}
        </ul>
      </div>
    <div>
  {% endif %}

  <hr/>

  <div style="text-align: center">
    Il reste {{ tournament.nbMatchLeft}} matchs à jouer
  </div>

  {% if is_granted('ROLE_ADMIN') and tournament.nbMatchLeft != 0 %}
    <a href="{{ path('simulateTournament', {'tournamentId' : tournament.id})}}">
      <div class="alert--info" style="text-align: center">
        SIMULER LE TOURNOI
      </div>
    </a>
  {% endif %}

  {% if tournament.isOpen == 1 and tournament.nbMatchLeft == 0 and is_granted(['ROLE_MANAGER', 'ROLE_ADMIN']) %}
    <a href="{{ path('finalRoundPrepar', {'tournamentId' : tournament.id})}}">
      <div class="alert--warning" style="text-align: center">
        La phase de groupe est finie,<br/>
        cliquez ici pour passer en phase finale
      </div>
    </a>
  {% endif %}

  <script type="text/javascript">

      $('.tabs-menu-link').click(function(){
        let target = $(this).attr('href');
        target = target.substr(1);

        // hide all show target
        $('.tabs-content-item').hide();
        $('#'+target).show();

        // change css on nav
        $('.tabs-menu-link').removeClass('is-active');
        $(this).addClass('is-active');

        return false;

      })

      if( "{{ tournament.competitionType}}" == "GROUP-ROUND"  ) {
        setInterval(function() {
          document.location.reload(true);
        }, 10000);
     }

  </script>


</div>

{% endblock %}