src/AppBundle/Entity/Person.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\User;

use DateTime;

/**
 * Person
 *
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PersonRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @author Sandy Razafitrimo <sandy@etsik.com>
 */
class Person extends LbmExtensionEntity
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=true)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=64, nullable=false)
     */
    private $lastname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="photo", type="string", length=256, nullable=true)
     */
    private $photo;

    /**
     * @var DateTime|null
     *
     * @ORM\Column(name="birthdate", type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @var Player
     *
     * @ORM\OneToOne(targetEntity="Player", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="player_id", referencedColumnName="id")
     */
    private $player;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFullname()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function getFullnameR()
    {
        return $this->lastname.' '.$this->firstname;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto(string $photo)
    {
        $this->photo = $photo;

        return $this;
    }

    public function getBirthdate()
    {
        return $this->birthdate;
    }

    public function setBirthdate($birthdate)
    {
          if (!$birthdate instanceof DateTime) {
              $birthdate = new DateTime($birthdate);
          }

      $this->birthdate = $birthdate;

      return $this;
    }

    public function getPlayer()
    {
        return $this->player;
    }


    public function setPlayer(Player $player)
    {
        $this->player = $player;
        $player->setPerson($this);
        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }


    public function getAge()
    {
        if($this->getBirthdate() == null) return null;
        $datetime1 = $this->getBirthdate();
        $datetime2 = new DateTime("now");
        $interval = $datetime1->diff($datetime2);
        return $interval->y;
    }

    public function toArray()
    {
      $objectArray = get_object_vars($this);
      return $objectArray;
    }

}

src/AppBundle/Entity/Player.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\Team;
use AppBundle\Entity\MatchDetails;

/**
 * Player
 *
 * // Nb : Architecture User > Person > Player in creation
 *        in use it can be player > person > user
 *
 * @ORM\Table(name="player")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PlayerRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Player extends LbmExtensionEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
      * @ORM\ManyToOne(targetEntity="SportPosition")
      * @ORM\JoinColumn(name="position_id", referencedColumnName="id", nullable=true)
      */
      private $position;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var string
     *
     * @ORM\Column(name="shirt_number", type="string", length=10, nullable=true)
     */
    private $shirtNumber;

    /**
    * @var ArrayCollection
    * @ORM\OneToMany(targetEntity="MatchDetails", mappedBy="player", cascade={"remove"}))
    * @ORM\OrderBy({"created_at" = "DESC"})
    */
    private $matchDetails;

    /**
     * @var Person
     *
     * @ORM\OneToOne(targetEntity="Person")
     * @ORM\JoinColumn(name="person_id", referencedColumnName="id")
     */
    private $person;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set position
     *
     * @param SportPosition
     *
     * @return Player
     */
    public function setPosition(SportPosition $position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return SportPosition
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Get position
     *
     * @return string
     */
    public function getPositionName()
    {
        return $this->getPosition()->getName();
    }

    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return Player
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Set shirtNumber
     *
     * @param string $shirtNumber
     *
     * @return Player
     */
    public function setShirtNumber($shirtNumber)
    {
        $this->shirtNumber = $shirtNumber;

        return $this;
    }

    /**
     * Get shirtNumber
     *
     * @return string
     */
    public function getShirtNumber()
    {
        return $this->shirtNumber;
    }


    public function getPerson()
    {
        return $this->person;
    }

    public function setPerson(Person $person)
    {
        $this->person = $person;

        return $this;
    }

    public function getSport()
    {
      return $this->getPosition()->getSport();
    }

    public function getSportName()
    {
      return $this->getSport()->getName();
    }

    public function toArray()
    {
      $objectArray = get_object_vars($this);

      return $objectArray;
    }
}

src/AppBundle/Entity/Team.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use AppBundle\Entity\Player;
use AppBundle\Entity\Tournament;

/**
 * Team
 *
 * // Nb : Architecture User > Person > Player in creation
 *        in use it can be player > person > user
 *
 * @ORM\Table(name="team")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TeamRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Team extends LbmExtensionEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="postal_code", type="string", length=255)
     */
    private $postalCode;

    /**
     * @var string
     *
     * @ORM\Column(name="sport_class", type="string", length=30, nullable=true)
     */
    private $sportClass;

    /**
     *
     * @ORM\ManyToMany(targetEntity="User", inversedBy="teams")
     * @ORM\JoinTable(name="teams_users")
     */
    private $users;

    /**
    * @ORM\ManyToOne(targetEntity="Sport")
    * @ORM\JoinColumn(name="sport_id", referencedColumnName="id", nullable=true)
    */
    private $sport;


    /**
     *
     * @ORM\ManyToMany(targetEntity="Tournament", mappedBy="teams")
     * @ORM\JoinTable(name="tournaments_teams")
     */
    private $tournaments;


    public function __construct()
    {
        $this->players = new ArrayCollection();
        $this->tournaments = new ArrayCollection();
        $this->users = new ArrayCollection();

    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Team
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Team
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function setSport(Sport $sport)
    {
        $this->sport = $sport;
        return $this;
    }

    public function getSport()
    {
        return $this->sport;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return Team
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set postalCode
     *
     * @param string $postalCode
     *
     * @return Team
     */
    public function setPostalCode($postalCode)
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * Get postalCode
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * Set sportClass
     *
     * @param string $sportClass
     *
     * @return Team
     */
    public function setSportClass($sportClass)
    {
        $this->sportClass = $sportClass;

        return $this;
    }

    /**
     * Get sportClass
     *
     * @return string
     */
    public function getSportClass()
    {
        return $this->sportClass;
    }

    public function addUser($user)
    {
        $this->users[] = $user;
        $user->addTeam($this);
        return $this;
    }

    public function removeUser($user)
    {
        $this->users->removeElement($user);
        return $this;
    }

    public function getUsers($role = null)
    {

        if($role) {
            $result = new ArrayCollection();
            foreach($this->users as $user) {
                if($user->getRoleString() == $role) $result[] = $user;
            }
            return $result;
        }
        return $this->users;
    }

    public function getCoachs()
    {
        return $this->getUsers('COACH');
    }

    public function getPlayers()
    {
        return $this->getUsers('PLAYER');
    }


    public function addTournament(Tournament $tournament)
    {
        $this->tournaments[] = $tournament;
        return $this;
    }

    public function getTournaments()
    {
        return $this->tournaments;
    }

    public function toArray()
    {
      $objectArray = get_object_vars($this);
      return $objectArray;
    }
}

src/AppBundle/Form/TeamType.php
<?php

namespace AppBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use AppBundle\Entity\Team;
use AppBundle\Form\PlayerType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;



class TeamType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
              ->add('name', TextType::class, ['label' => 'Nom'])
              ->add('description', TextareaType::class, ['required' => false])
              ->add('city', TextType::class, ['label' => 'Ville'] )
              ->add('postalCode', TextType::class, ['label' => 'Code Postal'])
              ->add('sport', EntityType::class, [
                                                     'label' => 'Sport',
                                                     'class' => 'AppBundle\Entity\Sport',
                                                     'choice_label' => 'name',
                                                     'required'   => false,])
              ->add('sportClass', TextType::class, ['label' => 'Catégorie']);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
          $resolver->setDefaults(array(
              'data_class' => Team::class
          ));
    }
}

src/AppBundle/Resources/views/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <h2>{{mode}} de l'équipe</h2>


    {{ form_start(form,  {'attr': {'id': 'edit-team'}}) }}
      <div class="flex-container--column">
          <div>
            {{ form_label(form.name)}}
            {{ form_widget(form.name)}}
            {{ form_errors(form.name)}}
          </div>

          <div>
            {{ form_label(form.description)}}
            {{ form_widget(form.description)}}
            {{ form_errors(form.description)}}
          </div>

          <div>
            {{ form_label(form.city)}}
            {{ form_widget(form.city)}}
            {{ form_errors(form.city)}}
          </div>

          <div>
            {{ form_label(form.postalCode)}}
            {{ form_widget(form.postalCode)}}
            {{ form_errors(form.postalCode)}}
          </div>

          <div>
          <h3 style="text-align: center">{{ form_label(form.sport)}}</h3>
            {{ form_widget(form.sport)}}
            {{ form_errors(form.sport)}}
          </div>

          <div>
            {{ form_label(form.sportClass)}}
            {{ form_widget(form.sportClass)}}
            {{ form_errors(form.sportClass)}}
          </div>

          <hr/>

          <input type="submit" class="btn--inverse" value="{{mode}}" />
      </div>
    {{ form_end(form)}}


{% endblock %}

src/AppBundle/Resources/views/team/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Liste des équipes</h1>
<hr/>

<h3 style="font-weight: bold">Mes équipes</h3>
<ul class="listElement">
  {% for team in owners %}
    <li class="listItem">
    <div><a href="{{ path('showTeam', {'teamId' : team.id })}}">{{team.name}}</a></div>
    </li>
  {% endfor %}
</ul>
<br/><br/>
<hr/>

<h3 style="font-weight: bold">Mes équipes associées</h3>
<ul class="listElement">
  {% for team in associates %}
    <li class="listItem">
    <div><a href="{{ path('showTeam', {'teamId' : team.id })}}">{{team.name}}</a></div>
    </li>
  {% endfor %}
</ul>
<br/><br/>



{% endblock %}

src/AppBundle/Resources/views/team/playersList.html.twig
<ul id="playersListTeamOl" style="columns: 2;">
  {% for user in users %}
    <li>
      <div>
        <b>{{user.person.player.shirtNumber}}</b>
        <span class="userPlayerName" id="userPlayerName-{{ user.id}}">
          {{ user.person.fullname}}
        </span>
        <div class="playersListTeam" id="playersListTeam-{{ user.id }}-{{ user.roleString|lower }}"
        style="float: right; color: darkred; width: 20px; font-weight: bold; cursor: pointer">x</div>
      </div>
      <i style="font-size: 10px">{{ user.person.player.positionName|capitalize}}</i>
    </li>
  {% endfor %}
</ul>
<script>
$('.playersListTeam').click(function() {
    var url = "{{ path('deletePlayerTeam')}}";
    var teamId = sessionStorage.getItem('teamId');
    var userId = $(this).attr('id').split('-')[1];
    var target = $(this).attr('id').split('-')[2];
    $('#'+target+'List').load(url+'/'+teamId+'/'+userId);
})

$('.userPlayerName').click(function() {
    $('#splashModal').toggle();
    let url = "{{ path('editPlayerForm')}}";
    let userId = $(this).attr('id').split('-')[1];
    $('#splashModalContent').load(url+'/'+teamId+'/ajaxCall/'+userId);
})
</script>

src/AppBundle/Resources/views/team/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
     <h1 id="nameTeam-details" class="listButtonTeam" style="cursor: pointer">{{team.name}}</h1>
    <div style="text-align: center">
        Créé par <b>{{ team.getCreatedBy.person.fullname}}</b>
    </div>

    <ul id="detailsList" style="display: none">
        <li class="listItem">
            <div style="font-size: 1.4em">
                <a href="{{ path('editTeam', {'id' : team.id})}}">
                    <i class="fas fa-edit" style="font-size: 1.4em; margin-right: 10px;"></i>
                </a>
                {{team.city}}
            </div>
        </li>
        <li style="text-align: justify">
            {{ team.description}}
        </li>
    </ul>

    <hr style="clear: both"/>
    <h3 style="font-weight: bold" class="listButton" id="listButton-coach">Liste des Coach.s</h3>
    <div id="coachList">
      {% include 'AppBundle:team:usersList.html.twig' with {'users': team.coachs} %}
    </div>
    <div style="display: flex">
        <i class="fas fa-plus-square" id="button-addCoach" style="font-size: 2.3em; margin-right: 10px;"></i>
        <input type="text" name="coach" placeholder="ajouter un.e coach" class="fullWidth" id="addCoach" style="display: none"/>
    </div>
    <div id="searchResult-addCoach"></div>

    <br/>
    <hr style="clear: both"/>
    <h3 style="font-weight: bold" class="listButton" id="listButton-player">
        <i class="fas fa-plus-square" id="button-addPlayer" style="font-size: 2.3em; margin-right: 10px; float: left"></i>
        Liste des Joueur.euse.s
    </h3>
    <br/>
    <div id="playerList">
      {% include 'AppBundle:team:playersList.html.twig' with {'users': team.players} %}
    </div>


    <script type="text/javascript">

        sessionStorage.removeItem('teamId');
        sessionStorage.setItem('teamId', "{{team.id}}");

        let teamId = "{{team.id}}";


        // ajax request coach
        var url = "{{ path('usersListAjax', {'role': 'ROLE_COACH'})}}";
        $('#addCoach').keyup(function() {
            var search = $('#addCoach').val();
            if(search.length > 0) {
                $('#searchResult-addCoach').load(url+'/'+search);
            }
        })

        $('#button-addPlayer').click(function() {
            $('#splashModal').toggle();
            let url = "{{ path('editPlayerForm')}}";
            $('#splashModalContent').load(url+'/'+teamId+'/ajaxCall');
        })


        $('.fa-plus-square').click(function() {
            let target = $(this).attr('id').split('-')[1];
            $('#'+target).toggle();
        })


        // toggle list function
        $('.listButtonTeam').click(function() {
            let target = $(this).attr('id').split('-')[1];
            $('#'+target+'List').toggle();
        })


    </script>


{% endblock %}

src/AppBundle/Resources/views/team/teamsListAjax.html.twig
<ul id="searchTeamsList">
  {% for team in teams %}
    <li class="searchTeamName" id="searchTeamId-{{team.id}}">{{ team.name}}</li>
  {% endfor %}
</ul>

<script type="text/javascript">
  $('.searchTeamName').click(function() {

      var url = "{{ path('addTeam')}}";
      var tournamentId = sessionStorage.getItem('tournamentId');
      var teamId = $(this).attr('id').split('-')[1];
      $('#searchTeamsList').html(' ');

      $('#teamList').load(url+'/'+tournamentId+'/'+teamId);
  })
</script>

src/AppBundle/Resources/views/team/usersList.html.twig
<ol style="columns: 2;">
  {% for user in users %}
    <li class="usersListTeam" id="usersListTeam-{{ user.id }}-{{ user.roleString|lower }}">{{ user.person.fullname}}</li>
  {% endfor %}
</ol>
<script>
$('.usersListTeam').click(function() {
    var url = "{{ path('deleteUserCoachAjax')}}";
    var teamId = sessionStorage.getItem('teamId');
    var userId = $(this).attr('id').split('-')[1];
    var target = $(this).attr('id').split('-')[2];
    $('#'+target+'List').load(url+'/'+teamId+'/'+userId);
})
</script>