src/AppBundle/Entity/Match.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\TournamentFinalRound;
use AppBundle\Entity\Team;
use AppBundle\Entity\Match;
use AppBundle\Entity\TournamentGroup;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Match
 *
 * @ORM\Table(name="match_game")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MatchRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Match extends LbmExtensionEntity
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
    * @ORM\ManyToOne(targetEntity="Team")
    * @ORM\JoinColumn(name="team_A_id", referencedColumnName="id")
    */
    private $teamA;

    /**
    * @ORM\ManyToOne(targetEntity="Team")
    * @ORM\JoinColumn(name="team_B_id", referencedColumnName="id")
    */
    private $teamB;

    /**
    * @ORM\ManyToOne(targetEntity="TournamentFinalRound", inversedBy="matchs")
    * @ORM\JoinColumn(name="final_round_id", referencedColumnName="id")
    */
    private $finalRound;

    /**
    * @ORM\ManyToOne(targetEntity="TournamentGroup", inversedBy="matchs")
    * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
    */
    private $group;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=50, nullable=true)
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="time_start", type="time",nullable=true)
     */
    private $timeStart;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="time_end", type="time",nullable=true)
     */
    private $timeEnd;

    /**
     * @var int
     *
     * @ORM\Column(name="position", type="integer", nullable=true)
     */
    private $position;

    /**
     * @var int
     *
     * @ORM\Column(name="pointA", type="integer", nullable=true)
     */
    private $pointA;

    /**
     * @var int
     *
     * @ORM\Column(name="pointB", type="integer", nullable=true)
     */
    private $pointB;

    /**
     * @var string
     *
     * @ORM\Column(name="winner", type="string", length=20, nullable=true)
     */
    public $winner;

    /**
     * @var string
     *
     * @ORM\Column(name="type_match", type="string", length=20, nullable=true)
     */
    public $typeMatch;

    /**
     *
     * @ORM\ManyToMany(targetEntity="User", inversedBy="matchs")
     * @ORM\JoinTable(name="matchs_users")
     */
    private $users;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function resetValues()
    {
        $this->setStatus('EMPTY');
        $this->setPointA(null);
        $this->setPointB(null);
        $this->setWinner(null);
        $this->setTimeStart(null);
        $this->setTimeEnd(null);

    }

    public function setTeamA(Team $team)
    {
        $this->teamA = $team;
        return $this;
    }

    public function getTeamA()
    {
        return $this->teamA;
    }

    public function setTeamB(Team $team)
    {
        $this->teamB = $team;
        return $this;
    }

    public function getTeamB()
    {
        return $this->teamB;
    }

    public function getTeamNameA()
    {
        return $this->getTeamName('teamA');
    }

    public function getTeamNameB()
    {
        return $this->getTeamName('teamB');
    }

    public function getTeamName($team)
    {
        $name = null;
        if($team == 'teamA' && $this->getTeamA()) $name = $this->getTeamA()->getName();
        if($team == 'teamB' && $this->getTeamB()) $name = $this->getTeamB()->getName();
        if($team == $this->getWinner()) {
          $name = "<span class='winner'>".$name.'</span>';
        }
        return $name;
    }

    public function setFinalRound(TournamentFinalRound $finalRound)
    {
        $this->finalRound = $finalRound;
        return $this;
    }

    public function getFinalRound()
    {
        return $this->finalRound;
    }

    public function setGroup(TournamentGroup $group)
    {
        $this->group = $group;
        return $this;
    }

    public function getGroup()
    {
        return $this->group;
    }

    public function getTournament()
    {
        if( $this->getGroup() ) return $this->getGroup()->getTournament();
        if( $this->getFinalRound() ) return $this->getFinalRound()->getTournament();
        return null;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return Match
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set timeStart
     *
     * @param \DateTime $time
     *
     * @return Match
     */
    public function setTimeStart($time)
    {
        $this->timeStart = $time;

        return $this;
    }

    /**
     * Get timeStart
     *
     * @return \DateTime
     */
    public function getTimeStart()
    {
        return $this->timeStart;
    }


    /**
     * Set timeEnd
     *
     * @param \DateTime $time
     *
     * @return Match
     */
    public function setTimeEnd($time)
    {
        $this->timeEnd = $time;

        return $this;
    }

    public function setTypeMatch($typeMatch)
    {
        $this->typeMatch = $typeMatch;
        return $this;
    }

    public function getTypeMatch()
    {
        return $this->typeMatch;
    }

    public function getTypeMatchString()
    {
      if($this->getTypeMatch() == "A") return "aller";
      if($this->getTypeMatch() == "R") return "retour";
      return null;

    }

    public function addUser($user)
    {
        $this->users[] = $user;
        $user->addMatch($this);
        return $this;
    }

    public function removeUser($user)
    {
        $this->users->removeElement($user);
        return $this;
    }

    public function getUsers($role = null)
    {
        if($role) {
          $result = new ArrayCollection;
            foreach($this->users as $user) {
                if($user->getRoleString() == $role) $result[] = $user;
            }
            return $result;
        }
        return $this->users;
    }

    public function getReferees()
    {
        return $this->getUsers('REFEREE');
    }

    public function getRefereeIdList()
    {
      if(!$referees = $this->getReferees()) return null;
      $arr = [];
      foreach($referees as $ref)
      {
        $arr[$ref->getId()] = $ref->getId();
      }
      return $arr;
    }

    /**
     * Get timeEnd
     *
     * @return \DateTime
     */
    public function getTimeEnd()
    {
        return $this->timeEnd;
    }

    /**
     * Set position
     *
     * @param integer $position
     *
     * @return Match
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }

    /**
     * Get position
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set pointA
     *
     * @param integer $pointA
     *
     * @return Match
     */
    public function setPointA($pointA)
    {
        $this->pointA = $pointA;

        return $this;
    }

    /**
     * Get pointA
     *
     * @return int
     */
    public function getPointA()
    {
        return $this->pointA;
    }

    /**
     * Set pointB
     *
     * @param integer $pointB
     *
     * @return Match
     */
    public function setPointB($pointB)
    {
        $this->pointB = $pointB;

        return $this;
    }

    public function getScore($separator = ' - ')
    {
        return $this->getPointA().$separator.$this->getPointB();
    }

    /**
     * Get pointB
     *
     * @return int
     */
    public function getPointB()
    {
        return $this->pointB;
    }

    /**
     * Set winner
     *
     * @param string $winner
     *
     * @return Match
     */
    public function setWinner($winner)
    {
        $this->winner = $winner;

        return $this;
    }

    public function getWinner()
    {
        return $this->winner;
    }



    /**
     * Get winner
     *
     * @return Team|null
     */
    public function getWinnerTeam()
    {
        if($this->winner == 'none') return 'none';
        if($this->winner == 'teamA') return $this->getTeamA();
        if($this->winner == 'teamB') return $this->getTeamB();
        return null;
    }

}

src/AppBundle/Entity/Person.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\User;

use DateTime;

/**
 * Person
 *
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PersonRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @author Sandy Razafitrimo <sandy@etsik.com>
 */
class Person extends LbmExtensionEntity
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=true)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=64, nullable=false)
     */
    private $lastname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="photo", type="string", length=256, nullable=true)
     */
    private $photo;

    /**
     * @var DateTime|null
     *
     * @ORM\Column(name="birthdate", type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @var Player
     *
     * @ORM\OneToOne(targetEntity="Player", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="player_id", referencedColumnName="id")
     */
    private $player;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFullname()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function getFullnameR()
    {
        return $this->lastname.' '.$this->firstname;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto(string $photo)
    {
        $this->photo = $photo;

        return $this;
    }

    public function getBirthdate()
    {
        return $this->birthdate;
    }

    public function setBirthdate($birthdate)
    {
          if (!$birthdate instanceof DateTime) {
              $birthdate = new DateTime($birthdate);
          }

      $this->birthdate = $birthdate;

      return $this;
    }

    public function getPlayer()
    {
        return $this->player;
    }


    public function setPlayer(Player $player)
    {
        $this->player = $player;
        $player->setPerson($this);
        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }


    public function getAge()
    {
        if($this->getBirthdate() == null) return null;
        $datetime1 = $this->getBirthdate();
        $datetime2 = new DateTime("now");
        $interval = $datetime1->diff($datetime2);
        return $interval->y;
    }

    public function toArray()
    {
      $objectArray = get_object_vars($this);
      return $objectArray;
    }

}

src/AppBundle/Controller/MatchController.php
<?php

 Namespace AppBundle\Controller;

 use Symfony\Bundle\FrameworkBundle\Controller\Controller;
 use Symfony\Component\HttpFoundation\Request;
 use Symfony\Component\HttpFoundation\JsonResponse;
 use Symfony\Component\Routing\Annotation\Route;
 use AppBundle\Entity\Tournament;
 use AppBundle\Entity\GameOptions;
 use AppBundle\Service\GameManager;
 use AppBundle\Entity\Match;
 use AppBundle\Entity\User;



 class MatchController extends Controller
 {

   /**
    * @Route("/match/{id}", name="showMatch")
    */
    public function showMatch(Request $request, $id)
    {
        $match = $this->getDoctrine()->getManager()->getRepository(Match::class)->find($id);
        return $this->render('AppBundle:match:show.html.twig', ['match' => $match]);
    }

    /**
     * @Route("/start-match/{id}", name="startMatch")
     */
    public function startMatch(Request $request, $id = null)
    {
        $id = $_GET['id'];

        $time = new \DateTime( date('H:i:s'));
        $em = $this->getDoctrine()->getManager();
        $match = $em->getRepository(Match::class)->find($id);
        $match->setStatus('START');
        $match->setTimeStart($time);
        $em->persist($match);
        $em->flush();

        return new JsonResponse( ['timeStart' => $time->format('H:i:s')]);
    }

    /**
     * @Route("/add-referre-match/{match_id}/{user_id}", name="addRefereeMatch")
     */
    public function addRefereeMatch(Request $request, $match_id = null, $user_id = null)
    {


        $em = $this->getDoctrine()->getManager();
        $match = $em->getRepository(Match::class)->find($match_id);
        $user = $em->getRepository(User::class)->find($user_id);

        $match->addUser($user);
        $em->persist($match);
        $em->flush();

        return new JsonResponse( ['referee' => $user->toArray()]);
    }

    /**
     * @Route("/remove-referre-match/{match_id}/{user_id}", name="removeRefereeMatch")
     */
    public function removeRefereeMatch(Request $request, $match_id = null, $user_id = null)
    {


        $em = $this->getDoctrine()->getManager();
        $match = $em->getRepository(Match::class)->find($match_id);
        $user = $em->getRepository(User::class)->find($user_id);

        $match->removeUser($user);
        $em->persist($match);
        $em->flush();

        return new JsonResponse( ['referee' => $user->toArray()]);
    }




    /**
     * @Route("/fin-de-match", name="endMatch")
     */
    public function endMatch(Request $request, GameManager $gameManager)
    {
        $match_id = $request->get('match_id');
        $score = $request->get('score');
        $point = explode('-', $score);
        $winner = $request->get('winner');

        $time = new \DateTime( date('H:i:s'));

        $em = $this->getDoctrine()->getManager();
        $match = $em->getRepository(Match::class)->find($match_id);

        $match->setWinner($winner);
        $match->setStatus('END');
        $match->setTimeEnd($time);

        $match->setPointA($point[0]);
        $match->setPointB($point[1]);

        $em->persist($match);
        $em->flush();

        $gameManager->updateRankingMatch($match);

        if($match->getGroup()) {
          $tournamentId = $match->getGroup()->getTournament()->getId();
          return $this->redirectToroute('showMatchGroup', ['tournamentId' => $tournamentId]);
        } else {
         $gameManager->updateFinalRoundMatch($match);
          $tournamentId = $match->getTournament()->getId();
          return $this->redirectToroute('showMatchFinalRound', ['tournamentId' => $tournamentId]);
        }


    }


 }

src/AppBundle/Resources/views/match/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% set displayStartButton = "display: none" %}

    <div class="messageModal alert--warning" id="flashMessage" style="margin-top: 10px; text-align: center; font-weight: bold; display: none">
    </div>

    <h1 class="matchH1">
        <span class="blueTitle">{{ match.teamA.name }}</span><br/>
        &nbsp;vs&nbsp;<br/>
        <span class="blueTitle">{{ match.teamB.name }}</span>
    </h1>

    <div id="refereeList">
        <h3>Arbitre.s</h3>
        {% if match.status == "END" %}
                <ul style="columns: 2;">
                {% for referee in match.referees %}
                    <li>{{ referee.person.fullname}}</li>
                {% endfor %}
                <ul>
        {% else %}
                {% if match.referees is empty %}
                        <div class="alert--warning" style="padding: 20px; font-size: 1.2em">
                            Il y a pas d'arbitre sur votre match,<br/>Ajoutez en pour démarrer.
                        </div>
                {% endif %}
                <ul id="listPerson">
                    {% for referee in match.tournament.referees %}
                        {% if referee.id in match.refereeIdList %}
                            {% set displayStartButton = "display: block" %}
                            <li id="refereeId-{{ referee.id}}" class="refereeName activeReferee">
                                {{ referee.person.fullname}}
                            </li>
                        {% else %}
                            <li id="refereeId-{{ referee.id}}" class="refereeName notActiveReferee">
                                {{ referee.person.fullname}}
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
        {% endif %}

        <button class="btn--primary fullWidth" id="startButton" style="cursor: pointer; {{ displayStartButton }}">
            Démarrer le match
        </button>
    </div>


    <div id="boardMatch" class="clearfix" style="display:none">
        <div id="time" style="width: 20%" class="fl">
          <span id="minuteStart">_</span>:<span id="secondeStart">_</span>
        </div>
        <div id="score" class="fr">
          <span id="pointA">0</span>
            :
          <span id="pointB">0</span>
        </div>
        <div id="iconTime" class="center">
            <span id="timeStart" style="font-size: 1.2em">
              {{ match.timeStart|date("H:i")}}
              {% if(match.timeEnd) %}
                &nbsp;-&nbsp;
                {{ match.timeEnd|date("H:i") }}
              {% endif %}
            </span>
        </div>
    </div>
    <hr style="float: none"/>

    <section class="grid-2-small-2">
      <div class="teamMatch">
          <h2>{{ match.teamA.name }}</h2>
          <h2 id="scoreA" style="float: right">0</h2>
          <hr style="float: none"/>
          <i class="fas fa-plus-square plusButton" id="plusTeam-A"></i>
          <i class="fas fa-minus-square minusButton" id="minusTeam-A"></i>
          <br  style="float: none"/>
      </div>
      <div class="teamMatch">
          <h2>{{ match.teamB.name }}</h2>
          <h2 id="scoreB" style="float: right">0</h2>
          <hr style="float: none"/>
          <i class="fas fa-plus-square plusButton" id="plusTeam-B"></i>
          <i class="fas fa-minus-square minusButton" id="minusTeam-B"></i>
          <br  style="float: none"/>
      </div>
    </section>

    <br/><br/>
    <form action="{{ path('endMatch')}}" method="post">
        <input type="hidden" name="match_id" value="{{ match.id}}"/>
        <input type="hidden" name="score" id="inputScore" value=""/>
        <input type="hidden" name="winner" id="inputWinner" value=""/>
        <input type="submit" class="btn--success fullWidth" id="validButton" style="cursor: pointer; display: none" value="Valider le résultat" />
    </form>

    <button class="btn--warning fullWidth" id="pauseButton" style="cursor: pointer; display: none">PAUSE</button>
    <br/><br/><br/>
    <button class="btn--danger fullWidth" id="endButton" style="cursor: pointer; display: none">Fin du match</button>


    <script type="text/javascript">

        let finalRound = "{{ match.tournament.competitionType }}";

        $('.refereeName').click(function(){
            let user_id = $(this).attr('id').split('-')[1];
            let match_id = "{{ match.id}}";
            let urlAddReferee = "{{ path('addRefereeMatch')}}";
            let urlRemReferee = "{{ path('removeRefereeMatch')}}";

            urlAddReferee = urlAddReferee+'/'+match_id+'/'+user_id;
            urlRemReferee = urlRemReferee+'/'+match_id+'/'+user_id;

            if(  $(this).hasClass('notActiveReferee')) {
                $.ajax({
                   url : urlAddReferee,
                   type : 'GET',
                   dataType : 'json',
                   success : function(data, statut){
                       let user_id = data['referee']['user_id'];
                       $('#refereeId-'+user_id).removeClass('notActiveReferee');
                       $('#refereeId-'+user_id).addClass('activeReferee');
                       $('#startButton').show();
                   }
                 })
            } else {
                $.ajax({
                   url : urlRemReferee,
                   type : 'GET',
                   dataType : 'json',
                   success : function(data, statut){
                       let user_id = data['referee']['user_id'];
                       $('#refereeId-'+user_id).removeClass('activeReferee');
                       $('#refereeId-'+user_id).addClass('notActiveReferee');
                   }
                 })
            }




        })

        var mStatus = "{{ match.status}}";

        if(mStatus == 'END')
        {
            var pointA = "{{ match.pointA }}";
            var pointB = "{{ match.pointB }}";

            $('#boardMatch').show();
            $('#startButton').hide();
            $('#time').hide();
            $('.plusButton').hide();
            $('.minusButton').hide();


            $('#pointA').html(pointA);
            $('#scoreA').html(pointA);
            $('#pointB').html(pointB);
            $('#scoreB').html(pointB);

        }

        sessionStorage.setItem('status', 'waiting');

        $('#startButton').click(function() {
            $.ajax({
                      method: "GET",
                      url: "{{ path('startMatch')}}",
                      data: { id: "{{ match.id}}" }
                  })
                  .done(function( data ) {

                      // hide and show
                      $('#boardMatch').show();
                      $('#startButton').hide();
                      $('#pauseButton').show();
                      $('#endButton').show();
                      $('#refereeList').hide();

                      // set time
                      sessionStorage.setItem('timeStart', data.timeStart);
                      $('#timeStart').html(data.timeStart);

                      $('#minuteStart').html(0);
                      $('#secondeStart').html(0);

                      let timerId = setInterval(timerCD, 1000);
                      sessionStorage.setItem('timerId', timerId);
                      sessionStorage.setItem('status', 'start');
                  });
        })

        $('#pauseButton').click(function() {
            let value = $('#pauseButton').html();

            if(value == 'PAUSE')
            {
              let timerId = sessionStorage.getItem('timerId');
              clearInterval(timerId);
              $('#pauseButton').html('RESTART');
              sessionStorage.setItem('status', 'pause');

            } else {
              let timerId = setInterval(timerCD, 1000);
              sessionStorage.setItem('timerId', timerId);
              $('#pauseButton').html('PAUSE');
              sessionStorage.setItem('status', 'start');

            }

        })

        $('#endButton').click(function() {

            let scoreA = parseInt($('#pointA').html());
            let scoreB = parseInt($('#pointB').html());

            if(scoreA == scoreB && finalRound == "FINAL-ROUND") {
                let message = 'Attention ! <br/>Vous ne pouvez pas avoir un match nul sur un tournoi à éliminination directe.';
                $('#flashMessage').html(message);
                $('#flashMessage').show();
                setTimeout(function() { $('#flashMessage').hide(); }, 5000);
            } else {
                let timerId = sessionStorage.getItem('timerId');
                clearInterval(timerId);
                $('#pauseButton').hide();
                $('#endButton').hide();
                $('#validButton').show();
                sessionStorage.setItem('status', 'end');
            }





        })

        $('.plusButton').click(function() {
            let status = sessionStorage.getItem('status');
            if(status != 'waiting')
            {
              let teamId = $(this).attr('id').split('-')[1].toUpperCase();
              let score = parseInt($('#point'+teamId).html());
              score = score + 1;
              $('#point'+teamId).html(score);
              $('#score'+teamId).html(score);
            }
        })

        $('.minusButton').click(function() {
            let status = sessionStorage.getItem('status');
            if(status != 'waiting')
            {
              let teamId = $(this).attr('id').split('-')[1].toUpperCase();
              let score = parseInt($('#point'+teamId).html());
              score = score - 1;
              if(score < 0) { score = 0};
              $('#point'+teamId).html(score);
              $('#score'+teamId).html(score);
            }
        })

        $('#validButton').click(function() {
          let scoreA = parseInt($('#pointA').html());
          let scoreB = parseInt($('#pointB').html());

          let winner = "none";

          if(scoreA > scoreB) {
            winner = "teamA";
          }

          if(scoreB > scoreA) {
            winner = "teamB";
          }

          $('#inputWinner').val(winner);
          $('#inputScore').val(scoreA+'-'+scoreB);

        })

        function timerCD() {
            let minute  = parseInt($('#minuteStart').html());
            let seconde = parseInt($('#secondeStart').html());
            seconde = seconde + 1;
            if(seconde == 60) {
               seconde = 0;
               minute = minute + 1;
            }
            $('#minuteStart').html(minute);
            $('#secondeStart').html(seconde);
        }

    </script>

{% endblock %}