src/AppBundle/Entity/Person.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\User;

use DateTime;

/**
 * Person
 *
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PersonRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @author Sandy Razafitrimo <sandy@etsik.com>
 */
class Person extends LbmExtensionEntity
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=true)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=64, nullable=false)
     */
    private $lastname;

    /**
     * @var string|null
     *
     * @ORM\Column(name="photo", type="string", length=256, nullable=true)
     */
    private $photo;

    /**
     * @var DateTime|null
     *
     * @ORM\Column(name="birthdate", type="date", nullable=true)
     */
    private $birthdate;

    /**
     * @var Player
     *
     * @ORM\OneToOne(targetEntity="Player", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="player_id", referencedColumnName="id")
     */
    private $player;

    /**
     * @var User
     *
     * @ORM\OneToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function getId()
    {
        return $this->id;
    }

    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFullname()
    {
        return $this->firstname.' '.$this->lastname;
    }

    public function getFullnameR()
    {
        return $this->lastname.' '.$this->firstname;
    }

    public function getLastname()
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto(string $photo)
    {
        $this->photo = $photo;

        return $this;
    }

    public function getBirthdate()
    {
        return $this->birthdate;
    }

    public function setBirthdate($birthdate)
    {
          if (!$birthdate instanceof DateTime) {
              $birthdate = new DateTime($birthdate);
          }

      $this->birthdate = $birthdate;

      return $this;
    }

    public function getPlayer()
    {
        return $this->player;
    }


    public function setPlayer(Player $player)
    {
        $this->player = $player;
        $player->setPerson($this);
        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }


    public function getAge()
    {
        if($this->getBirthdate() == null) return null;
        $datetime1 = $this->getBirthdate();
        $datetime2 = new DateTime("now");
        $interval = $datetime1->diff($datetime2);
        return $interval->y;
    }

    public function toArray()
    {
      $objectArray = get_object_vars($this);
      return $objectArray;
    }

}

src/AppBundle/Form/UserType.php
<?php

namespace AppBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


use Symfony\Component\OptionsResolver\OptionsResolver;
use AppBundle\Entity\User;


class UserType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
              ->add('email', EmailType::class, ['attr' => ['placeholder' => 'Email', 'autocomplete' => 'email-'.rand(1,10000)]])
              ->add('username', TextType::class, ['attr' => ['placeholder' => 'Username', 'autocomplete' => 'new-username-'.rand(1,10000)]])
              ->add('password', PasswordType::class, ['attr' => ['placeholder' => 'Mot de passe', 'autocomplete' => 'new-password']])
              ->add('roles', ChoiceType::class, ['choices' => [
                                                                                                  'Coach'              => 'ROLE_COACH',
                                                                                                  'Organisateur.trice' => 'ROLE_MANAGER',
                                                                                                   'Arbitre'           => 'ROLE_REFEREE',
                                                                                                  'Joueur.se'          => 'ROLE_PLAYER'
                                                                                             ]
                                                                    ])

              ->add('person', PersonType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
          $resolver->setDefaults(array(
              'data_class' => User::class
          ));
    }
}

src/AppBundle/Controller/UserController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use AppBundle\Entity\User;
use AppBundle\Form\UserPlayerType;
use AppBundle\Entity\Team;
use AppBundle\Entity\Sport;
use AppBundle\Entity\Person;
use AppBundle\Entity\Player;
use AppBundle\Entity\SportPosition;

use Symfony\Component\HttpFoundation\JsonResponse;





use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class UserController extends Controller
{

  private $em;

  public function __construct(EntityManagerInterface $em) {
    $this->em = $em;
  }


  /**
   * @Route("/users-list/{role}", name="usersList", defaults={"role": null})
   */
  public function usersList(Request $request, $role)
  {
      $users = $this->em->getRepository(User::class)->findByList($role);
      return $this->render('AppBundle:user:index.html.twig', ['users' => $users, 'role' => $role]);

  }

  /**
   * @Route("/show-user/{id}", name="showUser", defaults={"id": null})
   */
  public function showUser(Request $request, $id) {
    $user = $this->em->getRepository(User::class)->find($id);
    $editable = true;
    return $this->render('AppBundle:user:show.html.twig', ['user' => $user, 'editable' => $editable]);
  }

  /**
   * @Route("/creation-joueur/{team_id}/{type_call}/{user_id}", name="editPlayerForm", defaults={"user_id": null})
   */
  public function editPlayerForm(Request $request, UserPasswordEncoderInterface $encoder, $team_id = null, $type_call = null)
  {
    $em = $this->em;

    $user_id = $request->get('user_id');

    if($user_id) {
      $user = $em->getRepository(User::class)->find($user_id);
      $isNew = 0;
    } else {
      $user = new User();
      $isNew = 1;
    }
    $team = $em->getRepository(Team::class)->find($team_id);

    $sport = $team->getSport();

    $_SESSION['sport'] = $sport;

    $form = $this->createForm(UserPlayerType::class, $user);
    $form->handleRequest($request);

    if($form->isValid() && $form->isSubmitted())
    {
        $datas = $form->getData();

        if($isNew == 1) {
          $fname = strtolower(str_replace(array(' ',"'", '-', 'é', 'è', 'ï'), array('', '', '', 'e', 'e', 'i'), $datas->getPerson()->getFirstname()));
          $lname = ucfirst(strtolower(str_replace(array(' ',"'", '-', 'é', 'è', 'ï'), array('', '', '', 'e', 'e', 'i'), $datas->getPerson()->getLastname())));
          $username = $fname.$lname;
          $user->setUsername($username);
        }

        if($datas->getPassword() != "" || $datas->getPassword() != null) {
          $encoded = $encoder->encodePassword($user, $datas->getPassword());
          $user->setPassword($encoded);
        }

        $user->setRole([$datas->getRole()]);
        $em->persist($user);

        if($isNew == 1) {
          $team->addUser($user);
          $em->persist($team);
        }

        $em->flush();

        ($isNew == 1) ? $message = 'Compte créé ! Connexion possible' : $message = 'Compte mis à jour !';
        $this->addFlash('success', $message );
        return $this->redirectToRoute('login');
    }


    return $this->render('AppBundle:user:editPlayer.html.twig', ['form' => $form->createView(), 'type_call' => $type_call,'user_id' => $user_id, 'team_id' => $team_id, 'sport_name' => $sport->getName()]);
  }

  /**
   * @Route("/add-user-team-ajax", name="addUserTeamAjax")
   */
  public function addUserTeamAjax(Request $request, UserPasswordEncoderInterface $encoder)
  {

    $dt_user_player = $request->get('user_player');
    $dt_person = $dt_user_player['person'];
    $dt_player = $dt_person['player'];

    $em = $this->em;
    $team = $em->getRepository(Team::class)->find($request->get('team_id'));
    $position = $em->getRepository(SportPosition::class)->find($dt_player['position']);


    // player
    $player = new Player();
    $player->setPosition($position);
    $em->persist($player);

    // person
    $person = new Person();
    $person->setFirstname($dt_person['firstname']);
    $person->setLastname($dt_person['lastname']);
    $person->setBirthdate(new \DateTime($dt_person['birthdate']['year'].'-'.$dt_person['birthdate']['month'].'-'.$dt_person['birthdate']['day']));
    $em->persist($person);

    // user
    $user = new User();
    $encoded = $encoder->encodePassword($user, $dt_user_player['password']);
    $fname = strtolower(str_replace(array(' ',"'", '-', 'é', 'è', 'ï'), array('', '', '', 'e', 'e', 'i'), $person->getFirstname()));
    $lname = ucfirst(strtolower(str_replace(array(' ',"'", '-', 'é', 'è', 'ï'), array('', '', '', 'e', 'e', 'i'), $person->getLastname())));
    $username = $fname.$lname;

    // check username
    if($userExist = $this->em->getRepository(User::class)->findByUsername($username)) {
      $username = $username.'-'.date('his');
    }

    $user->setEmail($dt_user_player['email']);
    $user->setUsername($username);
    $user->setPassword($encoded);
    $user->setRoles([$dt_user_player['roles']]);
    $em->persist($user);

    $person->setPlayer($player);
    $user->setPerson($person);
    $team->addUser($user);
    $em->persist($team);
    $em->flush();

    return new JsonResponse(['player' => $user->toArray()]);

  }

  /**
   * @Route("/check-if-email-exist/{email}", name="userEmailExist")
   */
  public function userEmailExist($email = null)
  {
      if(!$user = $this->em->getRepository(User::class)->findByEmail($email))
      {
        return new JsonResponse(['user' => null]);
      } else {
        return new JsonResponse(['user' => $user->toArray()]);
      }

  }

  /**
   * @Route("/get-users-ajax/{role}/{search}", name="usersListAjax", defaults={"search" = null})
   */
  public function getUsersListAjax($role, $search)
  {
      $em = $this->getDoctrine()->getManager();
      $users = $em->getRepository(User::class)->findLike($role, $search);

      $role = strtolower(str_replace('ROLE_', '', $role));

      return $this->render('AppBundle:user:usersListAjax.html.twig', ['users' => $users, 'role' => $role]);

  }

}

src/AppBundle/Resources/views/user/editPlayer.html.twig
<div id="editPlayerModal">
  <h2>Création de Joueur.euse</h2>

  <div id="flashMessage" class="alert--success" style="display:none">
  </div>


  {{ form_start(form,  {'attr': {'id': 'edit-player'}}) }}
    <div class="flex-container--column">

        <input type="hidden" name="user_id" value="{{user_id}}" id="currentUserId"/>

        <input type="hidden" name="team_id" value="{{team_id}}" id="currentTeamId"/>

        <div>
          {{ form_widget(form.person.firstname)}}
          {{ form_errors(form.person.firstname)}}
        </div>

        <div>
          {{ form_widget(form.person.lastname)}}
          {{ form_errors(form.person.lastname)}}
        </div>

        <div>
          {{ form_widget(form.email)}}
          {{ form_errors(form.email)}}
        </div>

        <div id="emailProposal" style="font-size: 11px; font-style: italic; color: darkgrey">

        </div>

        <div>
          {{ form_widget(form.password)}}
          {{ form_errors(form.password)}}
        </div>
        <br/>
        <div>
          <h3 style="text-align: center">{{ form_label(form.person.birthdate)}}</h3>
          {{ form_widget(form.person.birthdate)}}
          {{ form_errors(form.person.birthdate)}}
        </div>
        <br/>
        <div>
          <h3 style="text-align: center">{{ sport_name }}</h3>
          <div style="text-align: center">
            {{ form_label(form.person.player.position)}}
          </div>
          {{ form_widget(form.person.player.position)}}
          {{ form_errors(form.person.player.position)}}
        </div>
        <div>
          {{ form_widget(form.person.player.shirtNumber)}}
          {{ form_errors(form.person.player.shirtNumber)}}
        </div>

        <hr/>
     </div>
  <input type="submit" class="btn--inverse" value="Créer" />

  {{ form_end(form)}}

</div>


{% if type_call == 'ajaxCall' %}
<script>

  let user_id = $('#currentUserId').val();
  if( user_id > 1) {
    $('#currentUserId').prop('required',false);
    console.log('hello');
  }

  $('#closeSplashModal').click(function() {
    let urlPlayerList = "{{ path('playerListTeam')}}";
    urlPlayerList = urlPlayerList+'/'+sessionStorage.getItem('teamId');
    $('#playerList').load(urlPlayerList);
  })

  $('#user_player_person_lastname').focusout(function() {
    let firstname = $('#user_player_person_firstname').val();
    let lastname = $('#user_player_person_lastname').val();
    $('#user_player_email').val(firstname.toLowerCase()+'.'+lastname.toLowerCase()+'@email.net');
    $('#emailProposal').html("Si le.a joueur.euse n'a pas d'email, laissez celui par défaut, il servira d'identifiant pour se connecter");
  })

  $('#user_player_email').focusout(function() {
    let userEmailExist = "{{ path('userEmailExist')}}";
    userEmailExist = userEmailExist+'/'+$('#user_player_email').val();
    $.ajax({
       url : userEmailExist,
       type : 'GET',
       dataType : 'json',
       success : function(data, statut){
         if(data['user'] != null) {
           $('#emailProposal').html('<span style="color: red">Cet email existe déjà, merci d\'en choisir un autre ou de retrouver votre compte</span>')
         } else {
           $('#emailProposal').html('<span style="color: green">Email accepté</span>');

         }
       }
     })


  })


  $('#edit-player').submit(function(e) {
    e.preventDefault();
     let data_str = $( "#edit-player" ).serialize();
     let url = "{{ path('addUserTeamAjax')}}";
     url = url+'?'+data_str;

     $.ajax({
        url : url,
        type : 'GET',
        dataType : 'json',
        success : function(data, statut){

          let player = data['player'];

            // update list Player
            let message = '<b>'+player['person']['firstname']+' '+player['person']['lastname']+'</b> a bien été ajouté à l\'équipe';
            message += '<br/> <span style="color: black">Vous pouvez ajouter un.e autre joueur.euse</span>'
            $('#flashMessage').show();
            $('#flashMessage').html(message);

            setTimeout(function(){
              $('#flashMessage').hide();
              $('#flashMessage').empty();
            }, 5000);

            // empty field
            $("#edit-player")[0].reset();
            $('#emailProposal').empty();

        }
     });



  })
</script>
{% endif %}

src/AppBundle/Resources/views/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h2>
  Utilisateurs Goome
</h2>

<div>
  <select name="role" id="selectRole" style="width: 100%; padding: 10px">
    <option value=""></value>
    <option value="ROLE_PLAYER" {{ selectOption('ROLE_PLAYER', role) }}>Joueur.se.s</value>
    <option value="ROLE_COACH" {{ selectOption('ROLE_COACH', role) }}>Coachs</value>
    <option value="ROLE_REFEREE" {{ selectOption('ROLE_REFEREE', role) }}>Arbitres</value>
    <option value="ROLE_MANAGER" {{ selectOption('ROLE_MANAGER', role) }}>Organisateur.trice.s</value>
  </select>
</div>

<div id="showCountRole">
</div>

<ul class="listElement">
  {% for user in users %}
    {% if user.roleString != "ADMIN" %}
      <li id="user-{{ user.id}}" class="listItem">
        <div>
          {{ user.showRoleUF|upper }}
        </div>
        <div>
          {{ user.person.fullnameR }}
        </div>
      </li>
    {% endif %}
  {% endfor %}
</ul>


{% endblock %}

{% block javascript %}
  <script>

    let nbItems = $('.listItem').length;
    $('#showCountRole').html(nbItems+' RESULTATS');

    let urlList     = "{{ path('usersList')}}";
    let urlShowUser = "{{ path('showUser')}}";

    // change role list
    $('#selectRole').change(function() {
        let role = $(this).val();
        $(location).attr('href', urlList+'/'+role);
    })
    $('.listItem').click(function() {
        let user_id = $(this).attr('id').split('-')[1];
        $('#splashModal').show();
        $('#splashModal')
        $('#splashModalContent').load(urlShowUser+'/'+user_id);
    })
  </script>
{% endblock %}

src/AppBundle/Resources/views/user/show.html.twig
<div id="showUserContent" style="margin:20px; font-size: 1.8em">
<div id="userPhoto">
  {% if user.person.photo is not null %}
    <img src="{{ asset(user.person.photo)}}"/>
  {% else %}
    <img src="{{ asset('images/person/anonymous.jpg')}}" style="border-radius: 180px; height: 200px; width: 200px"/>
  {% endif %}
</div>
<br/>
<h2>{{ user.person.fullname }}</h2>
<hr/>
<div style="display: flex; justify-content: space-between">
  <div id="userRole">{{ user.showRoleUF }}</div>
  <div id="userBirthdate">{{ user.person.age}} ans</div>
</div>

src/AppBundle/Resources/views/user/usersListAjax.html.twig
<ul id="searchUsersList">
  {% for user in users %}
    <li class="searchUserName" id="searchUserId-{{user.id}}">{{ user.person.fullname}}</li>
  {% endfor %}
</ul>

<script type="text/javascript">
  $('.searchUserName').click(function() {

      let role = "{{ role }}";

      if(role == "coach") {
        var url = "{{ path('addCoachTeam')}}";
        var targetId = sessionStorage.getItem('teamId');
      } else {
        var url = "{{ path('addUser')}}";
        var targetId = sessionStorage.getItem('tournamentId');
      }

      var userId = $(this).attr('id').split('-')[1];
      $('#searchUsersList').html(' ');
      $('#'+role+'List').load(url+'/'+targetId+'/'+userId);
  })
</script>